// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCRUD.DataAccess;

#nullable disable

namespace SimpleCRUD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241105143904_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCRUD.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 49,
                            DateOfBirth = new DateTime(1974, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Serhat Demircioğlu",
                            PhoneNumber = "+1 1774867925"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 44,
                            DateOfBirth = new DateTime(1979, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Gökçen Yılmaz",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Cem Yıldız",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 55,
                            DateOfBirth = new DateTime(1968, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Berke Doğan",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 70,
                            DateOfBirth = new DateTime(1953, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Hakan Tekin",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 70,
                            DateOfBirth = new DateTime(1953, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Özlem Kara",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 60,
                            DateOfBirth = new DateTime(1963, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Ediz Koç",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Arda Yalçın",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 53,
                            DateOfBirth = new DateTime(1970, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Ziya Çetinkaya",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 18,
                            DateOfBirth = new DateTime(2005, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Furkan Çelik",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Tesis Yönetimi",
                            FullName = "Ebru Çetiner",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 39,
                            DateOfBirth = new DateTime(1984, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Raşit Demirtaş",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 23,
                            DateOfBirth = new DateTime(2000, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operasyon",
                            FullName = "Selim Akgün",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Mete İçöz",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 50,
                            DateOfBirth = new DateTime(1973, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Arif Yıldırım",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Mert Kanada",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Age = 26,
                            DateOfBirth = new DateTime(1997, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Aylin Altun",
                            PhoneNumber = "+1 6395646874"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Age = 72,
                            DateOfBirth = new DateTime(1951, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Mustafa Yıldız",
                            PhoneNumber = "+1 1375269492"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Age = 64,
                            DateOfBirth = new DateTime(1959, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Seda Koç",
                            PhoneNumber = "+1 3458476129"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Age = 72,
                            DateOfBirth = new DateTime(1951, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Mühendislik",
                            FullName = "Cengiz Güneş",
                            PhoneNumber = "+1 4486306495"
                        },
                        new
                        {
                            EmployeeId = 21,
                            Age = 62,
                            DateOfBirth = new DateTime(1961, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Eren Toprak",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            EmployeeId = 22,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Furkan Doğan",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            EmployeeId = 23,
                            Age = 52,
                            DateOfBirth = new DateTime(1971, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Meltem İnce",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            EmployeeId = 24,
                            Age = 57,
                            DateOfBirth = new DateTime(1966, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Veri Analitiği",
                            FullName = "Serdar Kaplan",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            EmployeeId = 25,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Gökhan Kaya",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            EmployeeId = 26,
                            Age = 53,
                            DateOfBirth = new DateTime(1970, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Emir Özkan",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            EmployeeId = 27,
                            Age = 66,
                            DateOfBirth = new DateTime(1957, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Begüm Kurt",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            EmployeeId = 28,
                            Age = 55,
                            DateOfBirth = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Deniz Aydın",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            EmployeeId = 29,
                            Age = 26,
                            DateOfBirth = new DateTime(1997, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Oğuz Kaan",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            EmployeeId = 30,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Aslı Tuncel",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            EmployeeId = 31,
                            Age = 44,
                            DateOfBirth = new DateTime(1979, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İş Geliştirme",
                            FullName = "Burak Demir",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            EmployeeId = 32,
                            Age = 24,
                            DateOfBirth = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Çağla Sarı",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            EmployeeId = 33,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Yunus Emre",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            EmployeeId = 34,
                            Age = 37,
                            DateOfBirth = new DateTime(1986, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satın Alma",
                            FullName = "Okan Çelik",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            EmployeeId = 35,
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Ece Gündoğdu",
                            PhoneNumber = "+1 1824118974"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
