// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCRUD.DataAccess;

#nullable disable

namespace SimpleCRUD.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20241105191513_migfirst")]
    partial class migfirst
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCRUD.DataAccess.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 49,
                            DateOfBirth = new DateTime(1974, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Serhat Demircioğlu",
                            PhoneNumber = "+1 1774867925"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Age = 44,
                            DateOfBirth = new DateTime(1979, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Gökçen Yılmaz",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Cem Yıldız",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            EmployeeId = 4,
                            Age = 55,
                            DateOfBirth = new DateTime(1968, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Berke Doğan",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            EmployeeId = 5,
                            Age = 70,
                            DateOfBirth = new DateTime(1953, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Hakan Tekin",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            EmployeeId = 6,
                            Age = 70,
                            DateOfBirth = new DateTime(1953, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Özlem Kara",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            EmployeeId = 7,
                            Age = 60,
                            DateOfBirth = new DateTime(1963, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Ediz Koç",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            EmployeeId = 8,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Arda Yalçın",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            EmployeeId = 9,
                            Age = 53,
                            DateOfBirth = new DateTime(1970, 8, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Ziya Çetinkaya",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            EmployeeId = 10,
                            Age = 18,
                            DateOfBirth = new DateTime(2005, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Furkan Çelik",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            EmployeeId = 11,
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Tesis Yönetimi",
                            FullName = "Ebru Çetiner",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            EmployeeId = 12,
                            Age = 39,
                            DateOfBirth = new DateTime(1984, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Raşit Demirtaş",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            EmployeeId = 13,
                            Age = 23,
                            DateOfBirth = new DateTime(2000, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operasyon",
                            FullName = "Selim Akgün",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            EmployeeId = 14,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Mete İçöz",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            EmployeeId = 15,
                            Age = 50,
                            DateOfBirth = new DateTime(1973, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Arif Yıldırım",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            EmployeeId = 16,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Mert Kanada",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            EmployeeId = 17,
                            Age = 26,
                            DateOfBirth = new DateTime(1997, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Aylin Altun",
                            PhoneNumber = "+1 6395646874"
                        },
                        new
                        {
                            EmployeeId = 18,
                            Age = 72,
                            DateOfBirth = new DateTime(1951, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Halkla İlişkiler",
                            FullName = "Mustafa Yıldız",
                            PhoneNumber = "+1 1375269492"
                        },
                        new
                        {
                            EmployeeId = 19,
                            Age = 64,
                            DateOfBirth = new DateTime(1959, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Seda Koç",
                            PhoneNumber = "+1 3458476129"
                        },
                        new
                        {
                            EmployeeId = 20,
                            Age = 72,
                            DateOfBirth = new DateTime(1951, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Mühendislik",
                            FullName = "Cengiz Güneş",
                            PhoneNumber = "+1 4486306495"
                        },
                        new
                        {
                            EmployeeId = 21,
                            Age = 62,
                            DateOfBirth = new DateTime(1961, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Eren Toprak",
                            PhoneNumber = "+1 1280221170"
                        },
                        new
                        {
                            EmployeeId = 22,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Furkan Doğan",
                            PhoneNumber = "+1 6391420937"
                        },
                        new
                        {
                            EmployeeId = 23,
                            Age = 52,
                            DateOfBirth = new DateTime(1971, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Meltem İnce",
                            PhoneNumber = "+1 1634119861"
                        },
                        new
                        {
                            EmployeeId = 24,
                            Age = 57,
                            DateOfBirth = new DateTime(1966, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Veri Analitiği",
                            FullName = "Serdar Kaplan",
                            PhoneNumber = "+1 7644917715"
                        },
                        new
                        {
                            EmployeeId = 25,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Gökhan Kaya",
                            PhoneNumber = "+1 5082755411"
                        },
                        new
                        {
                            EmployeeId = 26,
                            Age = 53,
                            DateOfBirth = new DateTime(1970, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Emir Özkan",
                            PhoneNumber = "+1 5745426751"
                        },
                        new
                        {
                            EmployeeId = 27,
                            Age = 66,
                            DateOfBirth = new DateTime(1957, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Begüm Kurt",
                            PhoneNumber = "+1 5367480161"
                        },
                        new
                        {
                            EmployeeId = 28,
                            Age = 55,
                            DateOfBirth = new DateTime(1968, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Deniz Aydın",
                            PhoneNumber = "+1 2379992102"
                        },
                        new
                        {
                            EmployeeId = 29,
                            Age = 26,
                            DateOfBirth = new DateTime(1997, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Oğuz Kaan",
                            PhoneNumber = "+1 2495860935"
                        },
                        new
                        {
                            EmployeeId = 30,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Aslı Tuncel",
                            PhoneNumber = "+1 3911316611"
                        },
                        new
                        {
                            EmployeeId = 31,
                            Age = 44,
                            DateOfBirth = new DateTime(1979, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İş Geliştirme",
                            FullName = "Burak Demir",
                            PhoneNumber = "+1 5182461859"
                        },
                        new
                        {
                            EmployeeId = 32,
                            Age = 24,
                            DateOfBirth = new DateTime(1999, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Çağla Sarı",
                            PhoneNumber = "+1 2635917946"
                        },
                        new
                        {
                            EmployeeId = 33,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Yunus Emre",
                            PhoneNumber = "+1 5049298944"
                        },
                        new
                        {
                            EmployeeId = 34,
                            Age = 37,
                            DateOfBirth = new DateTime(1986, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satın Alma",
                            FullName = "Okan Çelik",
                            PhoneNumber = "+1 9252292089"
                        },
                        new
                        {
                            EmployeeId = 35,
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Ece Gündoğdu",
                            PhoneNumber = "+1 1824118974"
                        },
                        new
                        {
                            EmployeeId = 36,
                            Age = 41,
                            DateOfBirth = new DateTime(1982, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Yasemin Polat",
                            PhoneNumber = "+1 6178291847"
                        },
                        new
                        {
                            EmployeeId = 37,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Üretim",
                            FullName = "Bülent Karataş",
                            PhoneNumber = "+1 7259614823"
                        },
                        new
                        {
                            EmployeeId = 38,
                            Age = 49,
                            DateOfBirth = new DateTime(1974, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Muhasebe",
                            FullName = "Sibel Aydın",
                            PhoneNumber = "+1 3640916825"
                        },
                        new
                        {
                            EmployeeId = 39,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İş Geliştirme",
                            FullName = "Cenk Durmaz",
                            PhoneNumber = "+1 4762910483"
                        },
                        new
                        {
                            EmployeeId = 40,
                            Age = 28,
                            DateOfBirth = new DateTime(1995, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Deniz Özsoy",
                            PhoneNumber = "+1 5287369172"
                        },
                        new
                        {
                            EmployeeId = 41,
                            Age = 37,
                            DateOfBirth = new DateTime(1986, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satın Alma",
                            FullName = "Zehra Duman",
                            PhoneNumber = "+1 9842376184"
                        },
                        new
                        {
                            EmployeeId = 42,
                            Age = 58,
                            DateOfBirth = new DateTime(1965, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Serkan Özdemir",
                            PhoneNumber = "+1 6382047185"
                        },
                        new
                        {
                            EmployeeId = 43,
                            Age = 42,
                            DateOfBirth = new DateTime(1981, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Ceyda Çalışkan",
                            PhoneNumber = "+1 4861920743"
                        },
                        new
                        {
                            EmployeeId = 44,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Emre Taş",
                            PhoneNumber = "+1 2759816274"
                        },
                        new
                        {
                            EmployeeId = 45,
                            Age = 54,
                            DateOfBirth = new DateTime(1969, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Mehmet Karabacak",
                            PhoneNumber = "+1 1538476093"
                        },
                        new
                        {
                            EmployeeId = 46,
                            Age = 40,
                            DateOfBirth = new DateTime(1983, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Zeynep Gün",
                            PhoneNumber = "+1 5374829187"
                        },
                        new
                        {
                            EmployeeId = 47,
                            Age = 51,
                            DateOfBirth = new DateTime(1972, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Aslı Kılıç",
                            PhoneNumber = "+1 8391025739"
                        },
                        new
                        {
                            EmployeeId = 48,
                            Age = 45,
                            DateOfBirth = new DateTime(1978, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Tesis Yönetimi",
                            FullName = "Eren Özkan",
                            PhoneNumber = "+1 6247391085"
                        },
                        new
                        {
                            EmployeeId = 49,
                            Age = 27,
                            DateOfBirth = new DateTime(1996, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Mühendislik",
                            FullName = "Tuna Tekin",
                            PhoneNumber = "+1 2938165092"
                        },
                        new
                        {
                            EmployeeId = 50,
                            Age = 38,
                            DateOfBirth = new DateTime(1985, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Gizem Kaya",
                            PhoneNumber = "+1 5284017623"
                        },
                        new
                        {
                            EmployeeId = 51,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Hüseyin Çelik",
                            PhoneNumber = "+1 3461920847"
                        },
                        new
                        {
                            EmployeeId = 52,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Özge Kara",
                            PhoneNumber = "+1 5748392015"
                        },
                        new
                        {
                            EmployeeId = 53,
                            Age = 34,
                            DateOfBirth = new DateTime(1989, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Tolga Demir",
                            PhoneNumber = "+1 6174382915"
                        },
                        new
                        {
                            EmployeeId = 54,
                            Age = 48,
                            DateOfBirth = new DateTime(1975, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Melih Öz",
                            PhoneNumber = "+1 8291630482"
                        },
                        new
                        {
                            EmployeeId = 55,
                            Age = 29,
                            DateOfBirth = new DateTime(1994, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Muhasebe",
                            FullName = "Yelda Arslan",
                            PhoneNumber = "+1 2748193607"
                        },
                        new
                        {
                            EmployeeId = 56,
                            Age = 51,
                            DateOfBirth = new DateTime(1972, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Kerem Güçlü",
                            PhoneNumber = "+1 7251746384"
                        },
                        new
                        {
                            EmployeeId = 57,
                            Age = 25,
                            DateOfBirth = new DateTime(1998, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Gizem Koç",
                            PhoneNumber = "+1 6291843765"
                        },
                        new
                        {
                            EmployeeId = 58,
                            Age = 48,
                            DateOfBirth = new DateTime(1975, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Merve Aydın",
                            PhoneNumber = "+1 2851473912"
                        },
                        new
                        {
                            EmployeeId = 59,
                            Age = 32,
                            DateOfBirth = new DateTime(1991, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Burak Işık",
                            PhoneNumber = "+1 3917248375"
                        },
                        new
                        {
                            EmployeeId = 60,
                            Age = 56,
                            DateOfBirth = new DateTime(1967, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Seda Tunç",
                            PhoneNumber = "+1 1932487163"
                        },
                        new
                        {
                            EmployeeId = 61,
                            Age = 41,
                            DateOfBirth = new DateTime(1982, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Aylin Güven",
                            PhoneNumber = "+1 6394715286"
                        },
                        new
                        {
                            EmployeeId = 62,
                            Age = 33,
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Cem Karaca",
                            PhoneNumber = "+1 9274315078"
                        },
                        new
                        {
                            EmployeeId = 63,
                            Age = 52,
                            DateOfBirth = new DateTime(1971, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "İlker Kaya",
                            PhoneNumber = "+1 3871956240"
                        },
                        new
                        {
                            EmployeeId = 64,
                            Age = 43,
                            DateOfBirth = new DateTime(1980, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Mühendislik",
                            FullName = "Derya Ekinci",
                            PhoneNumber = "+1 7261847360"
                        },
                        new
                        {
                            EmployeeId = 65,
                            Age = 50,
                            DateOfBirth = new DateTime(1973, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İş Geliştirme",
                            FullName = "Cihan Arslan",
                            PhoneNumber = "+1 4871326059"
                        },
                        new
                        {
                            EmployeeId = 66,
                            Age = 35,
                            DateOfBirth = new DateTime(1988, 9, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Veri Analitiği",
                            FullName = "Ayhan Çelik",
                            PhoneNumber = "+1 3729146720"
                        },
                        new
                        {
                            EmployeeId = 67,
                            Age = 30,
                            DateOfBirth = new DateTime(1993, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Selma Özkan",
                            PhoneNumber = "+1 1837416583"
                        },
                        new
                        {
                            EmployeeId = 68,
                            Age = 60,
                            DateOfBirth = new DateTime(1963, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Sinan Yıldırım",
                            PhoneNumber = "+1 5273916428"
                        },
                        new
                        {
                            EmployeeId = 69,
                            Age = 47,
                            DateOfBirth = new DateTime(1976, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Eğitim ve Gelişim",
                            FullName = "Feride Eroğlu",
                            PhoneNumber = "+1 8467129354"
                        },
                        new
                        {
                            EmployeeId = 70,
                            Age = 28,
                            DateOfBirth = new DateTime(1995, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ürün Yönetimi",
                            FullName = "Onur Bayram",
                            PhoneNumber = "+1 6294712835"
                        },
                        new
                        {
                            EmployeeId = 71,
                            Age = 42,
                            DateOfBirth = new DateTime(1981, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Nilay Keskin",
                            PhoneNumber = "+1 9371246853"
                        },
                        new
                        {
                            EmployeeId = 72,
                            Age = 31,
                            DateOfBirth = new DateTime(1992, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Kalite Güvence",
                            FullName = "Esra Erkan",
                            PhoneNumber = "+1 4718392750"
                        },
                        new
                        {
                            EmployeeId = 73,
                            Age = 63,
                            DateOfBirth = new DateTime(1960, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Araştırma ve Geliştirme (Ar-Ge)",
                            FullName = "Mehmet Akça",
                            PhoneNumber = "+1 5273194826"
                        },
                        new
                        {
                            EmployeeId = 74,
                            Age = 36,
                            DateOfBirth = new DateTime(1987, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Operasyon",
                            FullName = "Rukiye Coşkun",
                            PhoneNumber = "+1 6182379450"
                        },
                        new
                        {
                            EmployeeId = 75,
                            Age = 48,
                            DateOfBirth = new DateTime(1975, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İdari İşler",
                            FullName = "Mete Bayat",
                            PhoneNumber = "+1 9732186405"
                        },
                        new
                        {
                            EmployeeId = 76,
                            Age = 24,
                            DateOfBirth = new DateTime(1999, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Hukuk",
                            FullName = "Nur Şahin",
                            PhoneNumber = "+1 8362815496"
                        },
                        new
                        {
                            EmployeeId = 77,
                            Age = 54,
                            DateOfBirth = new DateTime(1969, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Kerem Taş",
                            PhoneNumber = "+1 1924671530"
                        },
                        new
                        {
                            EmployeeId = 78,
                            Age = 39,
                            DateOfBirth = new DateTime(1984, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Destek",
                            FullName = "Sibel Özbek",
                            PhoneNumber = "+1 9387154260"
                        },
                        new
                        {
                            EmployeeId = 79,
                            Age = 44,
                            DateOfBirth = new DateTime(1979, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Veri Analitiği",
                            FullName = "Enes Kar",
                            PhoneNumber = "+1 5271938406"
                        },
                        new
                        {
                            EmployeeId = 80,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Özlem Aydın",
                            PhoneNumber = "+1 9238471562"
                        },
                        new
                        {
                            EmployeeId = 81,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Murat Kaya",
                            PhoneNumber = "+1 9238471563"
                        },
                        new
                        {
                            EmployeeId = 82,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Elif Yılmaz",
                            PhoneNumber = "+1 9238471564"
                        },
                        new
                        {
                            EmployeeId = 83,
                            Age = 41,
                            DateOfBirth = new DateTime(1983, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Ahmet Demir",
                            PhoneNumber = "+1 9238471565"
                        },
                        new
                        {
                            EmployeeId = 84,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Ayşe Karaca",
                            PhoneNumber = "+1 9238471566"
                        },
                        new
                        {
                            EmployeeId = 85,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Emre Can",
                            PhoneNumber = "+1 9238471567"
                        },
                        new
                        {
                            EmployeeId = 86,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Hizmetleri",
                            FullName = "Gözde Akın",
                            PhoneNumber = "+1 9238471568"
                        },
                        new
                        {
                            EmployeeId = 87,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Hakan Yıldız",
                            PhoneNumber = "+1 9238471569"
                        },
                        new
                        {
                            EmployeeId = 88,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Muhasebe",
                            FullName = "Seda Acar",
                            PhoneNumber = "+1 9238471570"
                        },
                        new
                        {
                            EmployeeId = 89,
                            Age = 40,
                            DateOfBirth = new DateTime(1984, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ar-Ge",
                            FullName = "Levent Çelik",
                            PhoneNumber = "+1 9238471571"
                        },
                        new
                        {
                            EmployeeId = 90,
                            Age = 31,
                            DateOfBirth = new DateTime(1993, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Deniz Şahin",
                            PhoneNumber = "+1 9238471572"
                        },
                        new
                        {
                            EmployeeId = 91,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Berkay Uzun",
                            PhoneNumber = "+1 9238471573"
                        },
                        new
                        {
                            EmployeeId = 92,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Esra Güven",
                            PhoneNumber = "+1 9238471574"
                        },
                        new
                        {
                            EmployeeId = 93,
                            Age = 42,
                            DateOfBirth = new DateTime(1982, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Selim Aksoy",
                            PhoneNumber = "+1 9238471575"
                        },
                        new
                        {
                            EmployeeId = 94,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 12, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Derya Öztürk",
                            PhoneNumber = "+1 9238471576"
                        },
                        new
                        {
                            EmployeeId = 95,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Hizmetleri",
                            FullName = "Onur Yavuz",
                            PhoneNumber = "+1 9238471577"
                        },
                        new
                        {
                            EmployeeId = 96,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Serap Akbulut",
                            PhoneNumber = "+1 9238471578"
                        },
                        new
                        {
                            EmployeeId = 97,
                            Age = 41,
                            DateOfBirth = new DateTime(1983, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Canan Özdemir",
                            PhoneNumber = "+1 9238471579"
                        },
                        new
                        {
                            EmployeeId = 98,
                            Age = 29,
                            DateOfBirth = new DateTime(1995, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ar-Ge",
                            FullName = "Metin Alkan",
                            PhoneNumber = "+1 9238471580"
                        },
                        new
                        {
                            EmployeeId = 99,
                            Age = 36,
                            DateOfBirth = new DateTime(1988, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Muhasebe",
                            FullName = "Gizem Kılıç",
                            PhoneNumber = "+1 9238471581"
                        },
                        new
                        {
                            EmployeeId = 100,
                            Age = 39,
                            DateOfBirth = new DateTime(1985, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Tamer Çetin",
                            PhoneNumber = "+1 9238471582"
                        },
                        new
                        {
                            EmployeeId = 101,
                            Age = 32,
                            DateOfBirth = new DateTime(1992, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Zeynep Şen",
                            PhoneNumber = "+1 9238471583"
                        },
                        new
                        {
                            EmployeeId = 102,
                            Age = 40,
                            DateOfBirth = new DateTime(1984, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Finans",
                            FullName = "Furkan Tekin",
                            PhoneNumber = "+1 9238471584"
                        },
                        new
                        {
                            EmployeeId = 103,
                            Age = 31,
                            DateOfBirth = new DateTime(1993, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Satış",
                            FullName = "Ceren Koç",
                            PhoneNumber = "+1 9238471585"
                        },
                        new
                        {
                            EmployeeId = 104,
                            Age = 38,
                            DateOfBirth = new DateTime(1986, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Müşteri Hizmetleri",
                            FullName = "Yusuf Er",
                            PhoneNumber = "+1 9238471586"
                        },
                        new
                        {
                            EmployeeId = 105,
                            Age = 34,
                            DateOfBirth = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "İnsan Kaynakları (İK)",
                            FullName = "Ece Aydın",
                            PhoneNumber = "+1 9238471587"
                        },
                        new
                        {
                            EmployeeId = 106,
                            Age = 37,
                            DateOfBirth = new DateTime(1987, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Lojistik",
                            FullName = "Selda Çelik",
                            PhoneNumber = "+1 9238471588"
                        },
                        new
                        {
                            EmployeeId = 107,
                            Age = 33,
                            DateOfBirth = new DateTime(1991, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Ar-Ge",
                            FullName = "Rıza Tan",
                            PhoneNumber = "+1 9238471589"
                        },
                        new
                        {
                            EmployeeId = 108,
                            Age = 41,
                            DateOfBirth = new DateTime(1983, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Muhasebe",
                            FullName = "Mine Sezer",
                            PhoneNumber = "+1 9238471590"
                        },
                        new
                        {
                            EmployeeId = 109,
                            Age = 35,
                            DateOfBirth = new DateTime(1989, 6, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Bilgi Teknolojileri (BT)",
                            FullName = "Emel Korkmaz",
                            PhoneNumber = "+1 9238471591"
                        },
                        new
                        {
                            EmployeeId = 110,
                            Age = 30,
                            DateOfBirth = new DateTime(1994, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Pazarlama",
                            FullName = "Orhan Öz",
                            PhoneNumber = "+1 9238471592"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
